[tools]
usage = "latest"
node = "24"
bun = "1"
deno = "2"
java = "oracle-25"
maven = "latest"
gradle = "latest"
eza = "latest"
jq = "latest"
# https://www.lazyvim.org/installation
neovim = "latest"
lazydocker = "latest"
lazygit = "latest"
fd = "latest"
